// FAKE DATA

import { buildQueries } from "@testing-library/react"

export const phones = [
  {
    id: 1,
    name: "iPhone 13 Pro",
    url: "https://www.mintmobile.com/wp-content/uploads/2021/09/iPhone_13_Pro_Gold_Pure_Back_iPhone_13_Pro_Gold_Pure_Front_2-up_Screen__USEN-copy.png",
    originalPrice: 1199.99,
    salePrice: 999.99,
    rating: 5,
    reviews: 37,
    os: "iOS",
    summary: "",
    colors: ["Sierra Blue,", "Gold,", "Silver,", "Graphite,", "Alpine Green"],
  },
  {
    id: 2,
    name: "iPhone 13",
    url: "https://www.mintmobile.com/wp-content/uploads/2021/09/iPhone_13_Midnight_Pure_Back_iPhone_13_Midnight_Pure_Front_2-up_Screen__USEN-copy-1.png",
    originalPrice: 899.99,
    salePrice: null,
    rating: 4.5,
    reviews: 30,
    os: "iOS",
    summary: "",
    colors: "Pink, Blue, Midnight, Starlight, Red, and Green",
  },
  {
    id: 3,
    name: "iPhone 12",
    url: "https://www.mintmobile.com/wp-content/uploads/2021/07/small_iPhone_12_Black_Pure_Front_iPhone_12_Black_Pure_Back_2-Up_Screen__USEN_transparent-new.png",
    originalPrice: 749.99,
    salePrice: 699.99,
    rating: 4.5,
    reviews: 17,
    os: "iOS",
    summary: "",
    colors: "White, Black, Blue, Green, Red, and Purple",
  },
  {
    id: 4,
    name: "iPhone 12 Mini",
    url: "https://www.mintmobile.com/wp-content/uploads/2021/06/iphone_12_mini_blue_tran.png",
    originalPrice: 699.99,
    salePrice: 649.99,
    rating: 4.5,
    reviews: 21,
    os: "iOS",
    summary: "",
    colors: "White, Black, Blue, Green, and Purple",
  },
  {
    id: 5,
    name: "iPhone 11",
    url: "https://www.mintmobile.com/wp-content/uploads/2021/11/iPhone_11_Green_PDP_Image_Position_2@1x.png",
    originalPrice: 549.99,
    salePrice: 499.99,
    rating: 5,
    reviews: 26,
    os: "iOS",
    summary: "",
    colors: "Black, Purple, Green, White, and Red",
  },
  {
    id: 6,
    name: "Google Pixel 5a",
    url: "https://www.mintmobile.com/wp-content/uploads/2022/03/google-pixel-5a.png",
    originalPrice: 599.99,
    salePrice: null,
    rating: 5,
    reviews: 6,
    os: "Android",
    summary: "",
    colors: "Black",
  },
  {
    id: 7,
    name: "Samsung Galaxy S21 5G",
    url: "https://ss73.vzw.com/is/image/VerizonWireless/02-samsung-palette-gray?hei=262",
    originalPrice: 899.99,
    salePrice: 749.99,
    rating: 5,
    reviews: 12,
    os: "Android",
    summary: "",
    colors: "Phantom Gray, Phantom Violet, Phantom Pink, and Phantom White",
  },
  {
    id: 8,
    name: "Samsung Galaxy S22",
    url: "https://ss73.vzw.com/is/image/VerizonWireless/samsung-rainbow-r0-128-gb-pink-gold-sms901uidv?hei=262",
    originalPrice: 1049.99,
    salePrice: 949.99,
    rating: 4.5,
    reviews: 18,
    os: "Android",
    summary: "",
    colors: "Pink Gold, Phantom White, Phantom Black, and Green",
  },
  {
    id: 9,
    name: "Google Pixel 6",
    url: "https://ss7.vzw.com/is/image/VerizonWireless/google-pixel-6-oriole-128-gb-carbon-ga02300-us?hei=262",
    originalPrice: 799.99,
    salePrice: 749.99,
    rating: 4,
    reviews: 29,
    os: "Android",
    summary: "",
    colors: "Stormy Black, and Sorta Seafoam",
  },
  {
    id: 10,
    name: "iPhone SE (3rd gen)",
    url: "https://ss71.vzw.com/is/image/VerizonWireless/apple-iphone-se-midnight-2022?hei=262",
    originalPrice: 449.99,
    salePrice: 399.99,
    rating: 5,
    reviews: 32,
    os: "iOS",
    summary: "",
    colors: "Midnight, Starlight, and Product Red",
  },
  {
    id: 11,
    name: "Samsung Galaxy A42 5G",
    url: "https://ss71.vzw.com/is/image/VerizonWireless/samsung-galaxy-a42-5g-smartphone-black-sma426uzkv?hei=262",
    originalPrice: 399.99,
    salePrice: null,
    rating: 4,
    reviews: 7,
    os: "Android",
    summary: "",
    colors: "Prism Dot Black",
  },
  {
    id: 12,
    name: "iPhone 11 Pro",
    url: "https://ss72.vzw.com/is/image/VerizonWireless/Apple_iPhone_11_Pro_Gold_09102019?hei=262",
    originalPrice: 599.99,
    salePrice: null,
    rating: 5,
    reviews: 36,
    os: "iOS",
    summary: "",
    colors: "Silver, Green, Gray, and Gold",
  },
];
